"""Integration tests for the bounded editing and testing state machine."""

from __future__ import annotations

import subprocess
import sys
import threading
from pathlib import Path

from hybrid_sdlc.aider_runner import run_bounded_loop
from hybrid_sdlc.command_profiles import CommandProfile
from hybrid_sdlc.models import RunStatus


def _setup_git_repo(path: Path) -> None:
    subprocess.run(["git", "init"], cwd=str(path), check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.name", "Tester"],
        cwd=str(path),
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.email", "test@test.com"],
        cwd=str(path),
        check=True,
        capture_output=True,
    )
    # Keep fake helpers and test-generated bytecode out of the review patch.
    gitignore = path / ".gitignore"
    gitignore.write_text("helpers/\n__pycache__/\n*.pyc\n", encoding="utf-8")
    init_file = path / "README.md"
    init_file.write_text("initial", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=str(path), check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", "initial commit"], cwd=str(path), check=True, capture_output=True
    )


def _commit_file(path: Path, filename: str) -> None:
    subprocess.run(["git", "add", filename], cwd=str(path), check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", f"add {filename}"], cwd=str(path), check=True, capture_output=True
    )


def test_bounded_loop_baseline_failure_aborts(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")

    # Command profile that immediately fails
    py_name = Path(sys.executable).name
    profile = CommandProfile(
        name="failing_profile",
        argv=[py_name, "-c", "import sys; sys.exit(1)"],
        cwd=".",
        timeout_seconds=10,
    )

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-001",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        max_retries=3,
    )

    assert result.status == RunStatus.FAILURE
    assert result.failure is not None
    assert result.failure.code == "BASELINE_TEST_FAILED"
    assert len(result.attempts) == 0


def test_bounded_loop_success(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")

    # A fake aider script placed under ignored helpers/
    helpers_dir = tmp_path / "helpers"
    helpers_dir.mkdir()
    fake_aider = helpers_dir / "fake_aider.py"
    fake_aider.write_text(
        "import sys\n"
        "with open('solution.py', 'w') as f:\n"
        "    f.write('def answer(): return 42\\n')\n"
        "sys.exit(0)\n",
        encoding="utf-8",
    )

    # Test profile checks solution.py exists and returns 42
    py_name = Path(sys.executable).name
    profile = CommandProfile(
        name="test_solution",
        argv=[
            py_name,
            "-c",
            "import os, sys\n"
            "if not os.path.exists('solution.py'): sys.exit(0)\n"
            "import solution; assert solution.answer() == 42; print('ALL PASS')",
        ],
        cwd=".",
        timeout_seconds=10,
    )

    (tmp_path / "README.md").write_text("source checkout edit", encoding="utf-8")
    (tmp_path / "untracked.txt").write_text("keep me", encoding="utf-8")
    subprocess.run(["git", "add", "README.md"], cwd=tmp_path, check=True, capture_output=True)
    source_index = subprocess.run(
        ["git", "diff", "--cached", "--binary"], cwd=tmp_path, check=True, capture_output=True
    ).stdout
    source_head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=tmp_path, check=True, capture_output=True, text=True
    ).stdout.strip()
    source_readme = (tmp_path / "README.md").read_bytes()
    source_status = subprocess.run(
        ["git", "status", "--porcelain=v1"],
        cwd=tmp_path,
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-002",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        max_retries=3,
        aider_cmd=[sys.executable, str(fake_aider)],
        commit_requested=True,
    )

    assert result.status == RunStatus.SUCCESS
    assert result.baseline_commit is not None
    assert result.initial_status == "clean"
    assert len(result.attempts) == 1
    assert result.attempts[0].test_passed
    assert result.final_diff is not None
    assert not result.final_diff.is_empty
    assert result.final_diff.changed_files == ["solution.py"]
    assert result.final_diff.patch_file is not None
    assert Path(result.final_diff.patch_file).is_absolute()
    assert result.source_repo_root == str(tmp_path.resolve())
    assert result.worktree_path is not None and Path(result.worktree_path).is_dir()
    assert result.review_patch == result.final_diff.patch_file
    assert Path(result.review_patch or "").is_file()
    assert "solution.py" in Path(result.review_patch or "").read_text(encoding="utf-8")
    assert result.commit_hash is not None
    assert (
        subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=result.worktree_path,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        == result.commit_hash
    )
    assert (
        subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=tmp_path, check=True, capture_output=True, text=True
        ).stdout.strip()
        == source_head
    )
    assert (tmp_path / "README.md").read_bytes() == source_readme
    assert (tmp_path / "untracked.txt").read_text(encoding="utf-8") == "keep me"
    assert (
        subprocess.run(
            ["git", "diff", "--cached", "--binary"],
            cwd=tmp_path,
            check=True,
            capture_output=True,
        ).stdout
        == source_index
    )
    assert (
        subprocess.run(
            ["git", "status", "--porcelain=v1"],
            cwd=tmp_path,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        == source_status
    )


def test_explicit_failure_rollback_removes_only_isolated_checkout(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")
    source_head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=tmp_path, check=True, capture_output=True, text=True
    ).stdout.strip()
    source_status = subprocess.run(
        ["git", "status", "--porcelain=v1"],
        cwd=tmp_path,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    helper = tmp_path / "helpers" / "failing_edit.py"
    helper.parent.mkdir()
    helper.write_text("from pathlib import Path; Path('broken.py').write_text('broken')\n")
    profile = CommandProfile(
        name="fail-after-edit",
        argv=[
            Path(sys.executable).name,
            "-c",
            "import pathlib, sys; sys.exit(pathlib.Path('broken.py').exists())",
        ],
    )

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-ROLLBACK",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        max_retries=1,
        aider_cmd=[sys.executable, str(helper)],
        rollback_on_failure=True,
    )

    assert result.status == RunStatus.FAILURE
    assert result.review_patch is not None
    assert "broken.py" in Path(result.review_patch).read_text(encoding="utf-8")
    assert result.worktree_path is not None and Path(result.worktree_path).is_dir()
    assert not (Path(result.worktree_path) / "broken.py").exists()
    assert (
        subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=tmp_path, check=True, capture_output=True, text=True
        ).stdout.strip()
        == source_head
    )
    assert (
        subprocess.run(
            ["git", "status", "--porcelain=v1"],
            cwd=tmp_path,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        == source_status
    )


def test_bounded_loop_stuck_identical_diff(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")

    # A fake aider script that makes the same edit every time, but tests fail
    helpers_dir = tmp_path / "helpers"
    helpers_dir.mkdir()
    fake_aider = helpers_dir / "fake_aider.py"
    fake_aider.write_text(
        "import sys\nwith open('bad.py', 'w') as f:\n    f.write('x = 1\\n')\nsys.exit(0)\n",
        encoding="utf-8",
    )

    py_name = Path(sys.executable).name
    profile = CommandProfile(
        name="test_fail",
        argv=[
            py_name,
            "-c",
            "import sys, os\n"
            "if not os.path.exists('bad.py'): sys.exit(0)\n"  # Baseline passes
            "sys.exit(1)\n",  # Once bad.py exists, test fails
        ],
        cwd=".",
        timeout_seconds=10,
    )

    source_head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=tmp_path, check=True, capture_output=True, text=True
    ).stdout.strip()
    source_status = subprocess.run(
        ["git", "status", "--porcelain=v1"],
        cwd=tmp_path,
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-003",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        max_retries=3,
        aider_cmd=[sys.executable, str(fake_aider)],
    )

    assert result.status == RunStatus.FAILURE
    assert result.failure is not None
    assert result.failure.code == "LOOP_STUCK"
    assert result.worktree_path is not None
    assert (Path(result.worktree_path) / "bad.py").is_file()
    assert result.review_patch is not None and Path(result.review_patch).is_file()
    assert (
        subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=tmp_path, check=True, capture_output=True, text=True
        ).stdout.strip()
        == source_head
    )
    assert (
        subprocess.run(
            ["git", "status", "--porcelain=v1"],
            cwd=tmp_path,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        == source_status
    )


def test_bounded_loop_zero_diff(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")
    helper = tmp_path / "helpers" / "no_edit.py"
    helper.parent.mkdir()
    helper.write_text("pass\n", encoding="utf-8")
    profile = CommandProfile(
        name="passing",
        argv=[Path(sys.executable).name, "-c", "print('pass')"],
    )

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-ZERO",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        aider_cmd=[sys.executable, str(helper)],
    )

    assert result.failure is not None
    assert result.failure.code == "LOOP_ZERO_DIFF"
    assert result.final_diff is not None
    assert result.final_diff.is_empty


def test_bounded_loop_aider_timeout(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")
    helper = tmp_path / "helpers" / "slow.py"
    helper.parent.mkdir()
    helper.write_text("import time\ntime.sleep(30)\n", encoding="utf-8")
    profile = CommandProfile(
        name="passing",
        argv=[Path(sys.executable).name, "-c", "print('pass')"],
    )

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-TIMEOUT",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        attempt_timeout_seconds=0.05,
        aider_cmd=[sys.executable, str(helper)],
    )

    assert result.failure is not None
    assert result.failure.code == "TASK_TIMEOUT"


def test_bounded_loop_baseline_cancellation(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")
    cancel = threading.Event()
    cancel.set()
    profile = CommandProfile(
        name="slow",
        argv=[Path(sys.executable).name, "-c", "import time; time.sleep(30)"],
    )

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-CANCEL",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        cancel_event=cancel,
    )

    assert result.status == RunStatus.CANCELLED
    assert result.failure is not None
    assert result.failure.code == "CANCELLED"


def test_bounded_loop_retry_exhaustion(tmp_path: Path) -> None:
    _setup_git_repo(tmp_path)
    spec = tmp_path / "spec.md"
    spec.write_text("# Spec", encoding="utf-8")
    _commit_file(tmp_path, "spec.md")
    helper = tmp_path / "helpers" / "increment.py"
    helper.parent.mkdir()
    helper.write_text(
        "from pathlib import Path\n"
        "p = Path('counter.txt')\n"
        "n = int(p.read_text()) + 1 if p.exists() else 1\n"
        "p.write_text(str(n))\n",
        encoding="utf-8",
    )
    test_code = (
        "from pathlib import Path; import sys; p=Path('counter.txt'); "
        "print(f'FAILED test_mod.py::test_case - failure {p.read_text()}' if p.exists() else 'ok'); "
        "sys.exit(1 if p.exists() else 0)"
    )
    profile = CommandProfile(
        name="changing-failure",
        argv=[Path(sys.executable).name, "-c", test_code],
    )

    result = run_bounded_loop(
        repo_root=tmp_path,
        spec_path=spec,
        task_id="TASK-RETRY",
        profile=profile,
        endpoint_url="http://127.0.0.1:8090/v1",
        model_name="Qwen",
        max_retries=3,
        aider_cmd=[sys.executable, str(helper)],
    )

    assert len(result.attempts) == 3
    assert result.failure is not None
    assert result.failure.code == "RETRY_EXHAUSTED"
