"""Tests for the Spec Kit initializer ownership manifest contract."""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

import pytest

from hybrid_sdlc.spec_initializer import (
    MANIFEST_RELATIVE_PATH,
    FileOwnership,
    ManagedFile,
    ManifestError,
    OwnershipManifest,
    classify_files,
    load_manifest,
    save_manifest,
    sha256_bytes,
    validate_managed_path,
)


def _record(path: str, content: bytes, source: bytes | None = None) -> ManagedFile:
    return ManagedFile(
        path=path,
        sha256=sha256_bytes(content),
        source_sha256=sha256_bytes(source) if source is not None else None,
    )


def test_manifest_serialization_is_deterministic_and_round_trips() -> None:
    first = _record(".specify/templates/spec-template.md", b"installed", b"source")
    second = _record(".specify/memory/constitution.md", b"rules")
    manifest = OwnershipManifest("0.1.0", (first, second))

    serialized = manifest.to_bytes()

    assert serialized.endswith(b"\n")
    assert serialized == manifest.to_bytes()
    assert OwnershipManifest.from_bytes(serialized) == manifest
    assert serialized.index(b"constitution.md") < serialized.index(b"spec-template.md")


def test_manifest_load_save_uses_dedicated_path_and_raw_hashes(tmp_path: Path) -> None:
    managed_path = ".specify/templates/spec-template.md"
    content = b"line one\r\nline two\n"
    destination = tmp_path.joinpath(*managed_path.split("/"))
    destination.parent.mkdir(parents=True)
    destination.write_bytes(content)
    manifest = OwnershipManifest("0.1.0", (_record(managed_path, content),))

    manifest_path = save_manifest(tmp_path, manifest)

    assert manifest_path.relative_to(tmp_path).as_posix() == MANIFEST_RELATIVE_PATH
    assert manifest_path.read_bytes() == manifest.to_bytes()
    assert load_manifest(tmp_path) == manifest


def test_classify_distinguishes_generated_modified_untracked_and_missing(tmp_path: Path) -> None:
    paths = [
        ".specify/templates/generated.md",
        ".specify/templates/customized.md",
        ".specify/templates/untracked.md",
        ".specify/memory/removed.md",
        ".specify/templates/not-created.md",
    ]
    contents = {
        paths[0]: b"generated bytes",
        paths[1]: b"user edit",
        paths[2]: b"created by user",
    }
    for relpath, content in contents.items():
        target = tmp_path.joinpath(*relpath.split("/"))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    manifest = OwnershipManifest(
        "0.1.0",
        (
            _record(paths[0], contents[paths[0]]),
            _record(paths[1], b"original"),
            _record(paths[3], b"gone"),
        ),
    )

    states = classify_files(tmp_path, manifest, paths)

    assert states == {
        paths[0]: FileOwnership.UNCHANGED_GENERATED,
        paths[1]: FileOwnership.MODIFIED_USER_OWNED,
        paths[2]: FileOwnership.UNTRACKED_USER_OWNED,
        paths[3]: FileOwnership.MISSING,
        paths[4]: FileOwnership.MISSING,
    }


@pytest.mark.parametrize(
    "bad_path",
    [
        "../outside.md",
        ".specify/templates/../../outside.md",
        "/.specify/templates/spec.md",
        "C:/repo/.specify/templates/spec.md",
        r".specify\templates\spec.md",
        ".specify//templates/spec.md",
        ".specify/templates/",
        ".hybrid_sdlc/secret.json",
        ".specify/templates/a.md:stream",
    ],
)
def test_managed_path_rejects_traversal_and_non_managed_paths(bad_path: str) -> None:
    with pytest.raises(ManifestError):
        validate_managed_path(bad_path)


def test_manifest_rejects_unknown_schema_and_extra_fields() -> None:
    with pytest.raises(ManifestError, match="unsupported manifest schema"):
        OwnershipManifest.from_bytes(b'{"schema_version":2,"toolkit_version":"0.1.0","files":[]}')
    with pytest.raises(ManifestError, match="only schema_version"):
        OwnershipManifest.from_bytes(
            b'{"schema_version":1,"toolkit_version":"0.1.0","files":[],"owner":"x"}'
        )


@pytest.mark.parametrize(
    "raw",
    [
        b"{",
        b'{"schema_version":true,"toolkit_version":"0.1.0","files":[]}',
        b'{"schema_version":1,"toolkit_version":"0.1.0","files":{}}',
        b'{"schema_version":1,"toolkit_version":"0.1.0","files":[{"path":".specify/templates/a.md"}]}',
        b'{"schema_version":1,"toolkit_version":"0.1.0","files":[],"files":[]}',
    ],
)
def test_manifest_rejects_malformed_data_and_duplicate_json_keys(raw: bytes) -> None:
    with pytest.raises(ManifestError):
        OwnershipManifest.from_bytes(raw)


def test_manifest_rejects_duplicate_paths_and_invalid_digest() -> None:
    digest = "a" * 64
    record = {"path": ".specify/templates/a.md", "sha256": digest}
    raw = json.dumps(
        {"schema_version": 1, "toolkit_version": "0.1.0", "files": [record, record]}
    ).encode()
    with pytest.raises(ManifestError, match="duplicate managed paths"):
        OwnershipManifest.from_bytes(raw)

    with pytest.raises(ManifestError, match="SHA-256"):
        ManagedFile(".specify/templates/a.md", "not-a-digest")


def test_manifest_rejects_bool_schema_version_in_direct_constructor() -> None:
    with pytest.raises(ManifestError, match="schema_version must be an integer"):
        OwnershipManifest("0.1.0", (), schema_version=True)


def test_load_manifest_returns_none_when_absent(tmp_path: Path) -> None:
    assert load_manifest(tmp_path) is None


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlinks are unavailable")
def test_classification_rejects_symlinked_managed_path(tmp_path: Path) -> None:
    outside = tmp_path.parent / f"{tmp_path.name}-outside"
    outside.mkdir()
    (outside / "edited.md").write_bytes(b"user data")
    managed = tmp_path / ".specify" / "templates"
    managed.parent.mkdir()
    try:
        managed.symlink_to(outside, target_is_directory=True)
    except OSError as exc:
        pytest.skip(f"cannot create symlink: {exc}")

    with pytest.raises(ManifestError, match="symlink"):
        classify_files(tmp_path, None, [".specify/templates/edited.md"])


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlinks are unavailable")
def test_load_manifest_rejects_symlinked_manifest(tmp_path: Path) -> None:
    specify = tmp_path / ".specify"
    specify.mkdir()
    outside = tmp_path / "outside.json"
    outside.write_bytes(OwnershipManifest("0.1.0", ()).to_bytes())
    path = tmp_path.joinpath(*MANIFEST_RELATIVE_PATH.split("/"))
    try:
        path.symlink_to(outside)
    except OSError as exc:
        pytest.skip(f"cannot create symlink: {exc}")

    with pytest.raises(ManifestError, match="symlink"):
        load_manifest(tmp_path)


@pytest.mark.skipif(os.name != "nt", reason="Windows junctions are Windows-specific")
@pytest.mark.parametrize(
    ("junction_relative", "target_inside_repo"),
    [
        (".specify", True),
        (".specify/templates", True),
        (".specify", False),
        (".specify/templates", False),
    ],
)
def test_classification_rejects_internal_and_escaping_junctions(
    tmp_path: Path,
    junction_relative: str,
    target_inside_repo: bool,
) -> None:
    junction = tmp_path.joinpath(*junction_relative.split("/"))
    junction.parent.mkdir(parents=True, exist_ok=True)
    target_root = (
        tmp_path / f"junction-target-{junction_relative.replace('/', '-')}"
        if target_inside_repo
        else tmp_path.parent / f"{tmp_path.name}-junction-target"
    )
    (target_root / "templates").mkdir(parents=True, exist_ok=True)
    (target_root / "templates" / "sample.md").write_bytes(b"user data")
    target = target_root if junction_relative == ".specify" else target_root / "templates"

    result = subprocess.run(
        ["cmd.exe", "/d", "/c", "mklink", "/J", str(junction), str(target)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        if not target_inside_repo:
            (target_root / "templates" / "sample.md").unlink()
            (target_root / "templates").rmdir()
            target_root.rmdir()
        pytest.skip(f"could not create Windows junction: {result.stderr or result.stdout}")

    try:
        with pytest.raises(ManifestError, match="reparse point"):
            classify_files(tmp_path, None, [".specify/templates/sample.md"])
    finally:
        # os.rmdir removes the junction itself; it never recursively deletes its target.
        os.rmdir(junction)
        if not target_inside_repo:
            (target_root / "templates" / "sample.md").unlink()
            (target_root / "templates").rmdir()
            target_root.rmdir()
